### ISSUE TITLE
通过这种方式没有授权文件也可以正常使用所有功能。希望官方可以修改下这个bug。

### ISSUE THREAD

**Issue by 736870598** [ksvc/KSYMediaEditorKit_Android#102]
在2.1的版本中，我通过下面这种方式可以绕过授权限制：

        AuthInfoManager.getInstance().setAuthInfo("任意不为空的字符串");
        AuthInfoManager.getInstance().checkAuth();
        try {
            AuthInfoManager instance = AuthInfoManager.getInstance();
            Field file = instance.getClass().getDeclaredField("c");
            file.setAccessible(true);
            Object oo = file.get(instance);
            Field a = oo.getClass().getDeclaredField("a");
            a.setAccessible(true);
            a.set(oo, AuthInfoManager.AUTH_SUCCESS);
            Field b = oo.getClass().getDeclaredField("b");
            b.setAccessible(true);
            b.set(oo, AuthInfoManager.FEA_BASE);
        } catch (Exception e) {
            e.printStackTrace();
        }

这样子我不需要通过授权就可以正常使用所有功能了。。。。。。。。不信你试试

**Comment by xingkai509** [comment]
非常感谢！我们尽快修复这个问题！
