### ISSUE TITLE
.so  包兼容问题，armeabi 或 v7a 在小米5s 上面的崩溃。内有详情

### ISSUE THREAD

**Issue by af913337456** [ksvc/KSYMediaEditorKit_Android#19]
小米5S PLUS
android6.0

只用 armeabi 或者 armeabi-v7a 点击录制就崩溃。

**Comment by af913337456** [comment]
见图片


![qq 20170626204634](https://user-images.githubusercontent.com/10436277/27540217-fc880b02-5ab1-11e7-9962-893e991dc22f.jpg)

**Comment by zanxiaofei** [comment]
添加abiFilter即可
