### ISSUE TITLE
感觉在合成视频的时候，很慢，有没有什么办法优化的 ？

### ISSUE THREAD

**Issue by 562218352** [ksvc/KSYMediaEditorKit_Android#22]

**Comment by chriszeng87** [comment]
原始视频是多长？合成花了多长时间？Demo可以复现？能把觉得慢的视频上传到一个网盘之类的地方，把url贴在这里么?

**Comment by 562218352** [comment]
demo里面合成的时候也是很慢，视频只有10秒左右，但是合成的时候需要很长时间才能合成好，现象是: 一开始合成的时候，进度很快就到60%或75%以上，但是再完后，进度就很慢了，一小会进度只增加1%到2%

**Comment by hlf2002** [comment]
我也遇到了这个问题。分段视频+背景音乐，速度超级慢。总共15秒的视频，要好几分钟才能合成好。

**Comment by chriszeng87** [comment]
抱歉，我们会在近期优化合成的速度

**Comment by 562218352** [comment]
谢谢，期待新版本的发布

**Comment by 562218352** [comment]
请问0.8版本有优化 合成速度很慢的问题吗？ 我更新到0.8版本后，合成速度没什么变化呀，还是很慢

**Comment by chriszeng87** [comment]
我们修复了一些bug，合成这块还在做重构，改动有些大，请再耐心等待一两个版本，谢谢

**Comment by chriszeng87** [comment]
请使用新版本，合成速度有比较大的提升。另外使用硬编的速度会更快，可以对比下画质，如果可以接受，也可以使用硬编，谢谢。合成速度会持续优化，请关注。
