### ISSUE TITLE
拍摄的最后1-2秒视频保存不下来

### ISSUE THREAD

**Issue by hlf2002** [ksvc/KSYMediaEditorKit_Android#24]
不光是整个视频的最后1-2秒，如果是分段的话，每个分段视频的最后1-2秒都保存不下来。

**Comment by hlf2002** [comment]
http://pan.baidu.com/s/1kVxDYn1

比如这个视频，采用分段拍摄，遇到2个问题：
1.合成之后，在总长度不变的情况下，视频变短了，因为每段的最后一点视频都被减掉，合成之后，总视频就短了很多；
2.合成速度超级慢。这个视频合成了超过2分钟才完成

**Comment by hlf2002** [comment]
我QQ:3142804

**Comment by chriszeng87** [comment]
我们复现下，如果有问题，会在下个版本修复，谢谢

**Comment by hlf2002** [comment]
非常感谢！祝金山云越来越棒！

**Comment by chriszeng87** [comment]
上个版本已修复，请参考 https://github.com/ksvc/KSYMediaEditorKit_Android/releases/tag/v1.0.4

**Comment by hlf2002** [comment]
@chriszeng87 并不是软编的最后一个视频丢失，而是不管软编硬编，不用合成，预览的时候就可以看到，每段视频的最后1-2秒录不下来。图像是卡在那里的。

**Comment by hlf2002** [comment]
你在按下暂停的时候，图像会卡在提前1-2秒的位置，预览的时候，就看到最后那1-2秒图像不动，有背景音。可以对比下抖音APP，他们录制的短视频，图像和声音是完美匹配上的。

**Comment by chriszeng87** [comment]
明白，你说的问题已经修复，你试下新版吧
