### ISSUE TITLE
在KSY_STREAMER_FILE_RECORD_STOPPED回调后马上start的问题

### ISSUE THREAD

**Issue by dandan9628** [ksvc/KSYMediaEditorKit_Android#38]
如标题，我在KSY_STREAMER_FILE_RECORD_STOPPED回调后开始startRecord的操作，视频会只录制258.0B，且无法正常打开，进度条正常，视频异常，请问这个是怎么回事?

**Comment by chriszeng87** [comment]
请参考下Demo
