### ISSUE TITLE
VIVO X9功能变速合成没有效果

### ISSUE THREAD

**Issue by yefawei** [ksvc/KSYMediaEditorKit_Android#40]
用Demo调整变速,合成后的视频没有任何变速效果

**Comment by yefawei** [comment]
使用的是540P,硬编,H.264,其它默认

**Comment by chriszeng87** [comment]
已修复，即将发布

**Comment by chriszeng87** [comment]
已上线  https://github.com/ksvc/KSYMediaEditorKit_Android/releases/tag/v1.1.2
