### ISSUE TITLE
希望在预览视频增加视频缩放方式

### ISSUE THREAD

**Issue by yefawei** [ksvc/KSYMediaEditorKit_Android#43]
希望在预览的时候增加预览缩放方式,有些手机在屏幕分辨率不同会出现黑边

**Comment by chriszeng87** [comment]
你希望是怎么样的呢?

**Comment by yefawei** [comment]
就是希望有 默认比例  按比例铺满  拉伸铺满  16:9  4:3等常用的缩放方式

**Comment by chriszeng87** [comment]
即将发布的版本会支持，请关注

**Comment by chriszeng87** [comment]
已上线 https://github.com/ksvc/KSYMediaEditorKit_Android/wiki/Video_Crop
