### ISSUE TITLE
1.1.2.1版本Demo运行不起来

### ISSUE THREAD

**Issue by yefawei** [ksvc/KSYMediaEditorKit_Android#46]
1.1.2.1版本Demo运行不起来,发现没有导入SO库

**Comment by chriszeng87** [comment]
你是Windows开发的？不是Mac OS 或者Linux/Unix?

**Comment by yefawei** [comment]
windows平台,libksysv-armv7a:1.1.2.1这些地址下载下来的东西都没有so库

**Comment by chriszeng87** [comment]
这个你自己解决一下吧，如果不是用jcenter引用，因为我们是软链接，你需要手动copy一下那些库
