### ISSUE TITLE
Video has laggy with KSYEditKit UHD Video

### ISSUE THREAD

**Issue by zaizaixinhtrai** [ksvc/KSYMediaEditorKit_Android#50]
I used KSYEditKit for edit video. But with video UHD 3840 × 2160 has laggy. I am using libksylive 2.4.1, ks3androidsdk:1.4.1
May I fix that ?. Thanks.

**Comment by chriszeng87** [comment]
The resolution is too high.... Could you give us the online link to the video?

**Comment by zaizaixinhtrai** [comment]
Pl download this video, thanks
https://drive.google.com/open?id=0Byw83FVsVYrbWnQ5MExPbzJpQjg

**Comment by chriszeng87** [comment]
4K is a very high resolution for mobile devices. This is not  normal case for mobile video editing app.
