### ISSUE TITLE
编辑视频把视频音量调0,还会有细微的声音,需要重新播放才行

### ISSUE THREAD

**Issue by yefawei** [ksvc/KSYMediaEditorKit_Android#51]
编辑视频把视频音量调0,还会有细微的声音
比如:有一个20秒的视频(本身有声音),在播到5秒时把视频音量调0,还会有细微的声音出来,需要播到20秒重头播放才会完全没有声音,如果中途又把音量调高,又调成0,又会有细微的声音

**Comment by zanxiaofei** [comment]
谢谢反馈，我们调查一下

**Comment by zanxiaofei** [comment]
1.2.2 已经解决
