### ISSUE TITLE
KSYEditKit 导致OOM，在onDestroy()中有调用release()方法的呀

### ISSUE THREAD

**Issue by zhangshaobo87** [ksvc/KSYMediaEditorKit_Android#90]
# main(1)
java.lang.OutOfMemoryError
Failed to allocate a 2097171 byte allocation with 1762744 free bytes and 1721KB until OOM

1 dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2 java.nio.DirectByteBuffer$MemoryRef.<init>(DirectByteBuffer.java:58)
3 java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:240)
4 com.ksyun.media.streamer.util.d.<init>(FrameBufferCache.java:23)
5 com.ksyun.media.streamer.encoder.AVCodecVideoEncoder.<init>(AVCodecVideoEncoder.java:31)
6 com.ksyun.media.shortvideo.kit.a.d(KSYComposeKit.java:171)
7 com.ksyun.media.shortvideo.kit.a.<init>(KSYComposeKit.java:134)
8 com.ksyun.media.shortvideo.kit.KSYEditKit.a(KSYEditKit.java:178)
9 com.ksyun.media.shortvideo.kit.KSYEditKit.<init>(KSYEditKit.java:144)

**Comment by zanxiaofei** [comment]
这像是系统内存不足导致分配失败了，本身的oom应该不是KSYEditKit 造成的  
麻烦说的细一点，什么时机出现的？什么版本？什么机型？

**Comment by zhangshaobo87** [comment]
不好意思
系统版本是：Android 7.0,level 24
机型：荣耀 DUK AL20
ROM : HuaWei/EMOTION
CPU架构：arm64-v8a

在视频编辑的时候出现的,是bugly收集的崩溃日志

**Comment by zanxiaofei** [comment]
崩溃的地方是合成的时候了，不是编辑预览的时候了，确认一下手机当时的内存情况吧？崩溃这个地方的内存申请并不是循环进行的，因此理论上应该不是这一处导致的oom，可以看一下全一点日志，看什么地方在循环申请内存
