### ISSUE TITLE
How can i remove Last Frame (Your Name & logo ) On Video Edited ??

### ISSUE THREAD

**Issue by Ronakgadhia** [ksvc/KSYMediaEditorKit_Android#97]
Once I edited all video changes and Press Right hand top side (Right icon) TO save Videos.It Automatically add your company logo as a last frame of all video.How can i remove it ? I don't want your company logo.Thanks in advance.

**Comment by zanxiaofei** [comment]
Please refer to:
https://github.com/ksvc/KSYMediaEditorKit_Android/wiki/add_title_tail

**Comment by Ronakgadhia** [comment]
OK.My Question is Why The last frame automatically adds when that edited video stored in sd card?

How can i prevent to add that last frame( Black Screen With Animated your company logo)?

**Comment by zanxiaofei** [comment]
do not call setTailUrl(String tailUrl)

**Comment by Ronakgadhia** [comment]
Okay. Thank you. Got it.
I am Closing this issue. 👍 :)
